name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: '${{matrix.node}} on ${{matrix.os}}'
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v4
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # To do: Add back when supported again <https://github.com/actions/setup-node/issues/1016>
          # - windows-latest
        node:
          - lts/gallium
          - node
